name: C++ Serial Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Run C++ Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Serial test_runner
        working-directory: src/serial_cpp
        # Compiling with standard C++17 to ensure it works identically across all modern g++ versions
        run: g++ -std=c++17 test_main.cpp contour_to_signal.cpp cleaning_and_boundary_extraction.cpp -o test_runner
        
      - name: Run Serial test_runner
        working-directory: src/serial_cpp
        run: ./test_runner

        # Instead of downloading nvcc every time we commit, we can cache it
      - name: Cache CUDA Toolkit (APT archives)
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-cuda-toolkit
          
      - name: Install CUDA Toolkit dependencies
        run: |
          sudo rm -f /var/cache/apt/archives/lock
          sudo apt-get update
          sudo apt-get install -y nvidia-cuda-toolkit
          
      - name: Compile CUDA test_runner
        working-directory: src/serial_cpp
        # We can only test cuda files by compiling them with nvcc
        # As there are no GPUs on GitHub Actions Servers
        run: nvcc -std=c++17 test_main.cpp ../parallel_cpp/contour_to_signal.cu -o cuda_test_runner
